### PR TITLE
Fix markdown not parsed in foldable details

### LINKED ISSUE #1074: [bug] Markdown not parsed in foldable details
Markdown is not parsed in foldable details html tag, e.g. on https://docs.fastlane.tools/actions/deliver/ 

Screenshot 2021-07-15 at 21 41 21

### PR DESCRIPTION
**Pull request by lucgrabowski**
### Motivation and Context
Resolves #1074
Markdown is not parsed in foldable details html tag, e.g. on https://docs.fastlane.tools/actions/deliver/

### Description
Added  `markdown.extensions.md_in_html` extension to parse markdown in html tags.
Used `markdown="1"` to parse markdown.

Fix based on:
https://github.com/mkdocs/mkdocs/issues/1687
https://python-markdown.github.io/extensions/md_in_html/

### Testing Steps
Install mkdocs locally, build site, check html pages.
Dear reviewer, please check if the changes in formatting are fine.

### CODE REVIEW

**Review by rogerluan — APPROVED** [review]
Your solution LGTM! I've tested a few pages and they all look good.
Thank you so much for spotting this and proposing the fix right away! ❤️  Really appreciate your contribution!

**Comment by janpio** [comment]
This unfortunately will be / would be undone via https://github.com/fastlane/docs/pull/1077/files - there has to be a template for this somewhere that defines the code to be generated - that needs to be updated.

**Comment by lucgrabowski** [comment]
@janpio Thanks for noticing that the change will be overriden by bot.
https://github.com/fastlane/fastlane/pull/19184 should fix it.

**Comment by janpio** [comment]
Unfortunately https://github.com/fastlane/docs/pull/1080/files is still build on the state before.

Should we merge it anyway and then the next release will fix it?

**Comment by lucgrabowski** [comment]
@joshdholtz please advise :) if https://github.com/fastlane/docs/pull/1080 should be merged.
For me, parsing foldable details could be temporarily broken if the release will be done soon.

**Comment by janpio** [comment]
I went ahead and merged #1080 - 2.190 will come soon enough.

**Comment by rogerluan** [comment]
Nice 👀 @janpio ! 🎉 thanks for spotting this since I failed to do so! 🙈 

I wish it was more obvious which files in this repo are auto-generated, like putting all of them in a `/generated` dir or something 😅

**Comment by janpio** [comment]
If you care, go for it. I definitely would have liked that in the past when I was more active and tried to change things more regularly. (Mgiht be that mkdocs doesn't make that easy though)

**Comment by rogerluan** [comment]
Yea I think it will be a tough fight with mkdocs 😕

**Comment by lucgrabowski** [comment]
@rogerluan 
I've added 2 PRs with the solution to moving documentation to `generated` directory and updating documentation generation:
https://github.com/fastlane/docs/pull/1091
https://github.com/fastlane/fastlane/pull/19309

**Comment by rogerluan** [comment]
Omg, that will make things so much safer and easier to review! I'll take a look when I can @lucgrabowski 🙏 thanks for this!! 🚀

**Pull request merged**
