### PR TITLE
[Bot] Update docs for latest fastlane release 2.179.0 (actions.md, available-plugins.md) 🚀

### PR DESCRIPTION
**Pull request by joshdholtz**
Auto-generated by _fastlane_ bot 🤖

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>mkdocs.yml</code> was modified - make sure no modification was made by mistake</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by janpio — APPROVED** [review]
The `match_nuke` action looks dangerous, but that is of course not super relevant for the docs @joshdholtz.

**Comment by joshdholtz** [comment]
@janpio Is it? 🤔 It shouldn't be more dangerous than calling `fastlane match nuke`

**Comment by joshdholtz** [comment]
I'd actually argue that it might leader to safer nuke practices since you don't have to manually type some of the options every time. You can hardcoded to nuke development instead of accidentally doing distribution.

**Comment by janpio** [comment]
Yeah that is very explicit vs. just having this in your Fastfile. At least that was my thought when reviewing this - not super sure if this feeling is real.

**Pull request merged**
