### PR TITLE
Update screenshots.md

### PR DESCRIPTION
**Pull request by aldoyh**
Broken link corrected

### CODE REVIEW

**Comment by rogerluan** [comment]
@aldoyh could you update the SLA according Google's message above? 🙏

**Comment by aldoyh** [comment]
Done ✅

**Comment by rogerluan** [comment]
@google-cla I signed!

**Comment by rogerluan** [comment]
@aldoyh it still shows that you haven't completed it 🤔 

>The following contributors were found for this pull request:
>
>❌ https://github.com/fastlane/docs/commit/63709d3126730c7da39ae6df910dea0f02be507e Author: @aldoyh <aldoyh​@users.noreply.github.com>
>
>(Only the first commit for a unique contributor is listed.)

Perhaps this could be a bug, could you close this PR and open a new one? 🙇 sorry for the inconvenience

**Pull request closed without merging**
