### PR TITLE
[supply] fix link leading to a 404 in Android's beta deployment page

### PR DESCRIPTION
**Pull request by jschmid**
The previous link leads to a 404.

### CODE REVIEW

**Review by rogerluan — COMMENTED** [review]
🤔 The current link works just fine for me, is it not working for you?

I went to https://docs.fastlane.tools/getting-started/android/beta-deployment/ and clicked on this link:

image


And it takes me here with no issues: https://docs.fastlane.tools/getting-started/android/setup/#setting-up-supply

image

Are you sure it's broken @jschmid ?

**Comment by jschmid** [comment]
@rogerluan I was actually confused when fixing the link. And I fixed the wrong one at first. 

You can now check that both links are fixed: https://deploy-preview-1215--fastlane-docs-preview.netlify.app/

**Review by rogerluan — APPROVED** [review]
Nice catch! Thanks for fixing it, now I see that both works 🤗 

Cheers!

**Comment by jschmid** [comment]
Looks like documentation has not been published for 7 months already 🤷 
https://app.circleci.com/pipelines/github/fastlane/docs?branch=master

**Comment by rogerluan** [comment]
Yes, there is an issue with our deployment that we haven't had the chance to fix yet 😞

**Comment by rogerluan** [comment]
cc @joshdholtz 🙏

**Comment by joshdholtz** [comment]
On it!

**Comment by joshdholtz** [comment]
Fixed!

**Comment by rogerluan** [comment]
The website deployment has been fixed (s/o to @joshdholtz ❤️ ) and your fix is now live @jschmid 🚀 Thanks once again for this fix! 🙌

**Pull request merged**
