### PR TITLE
Update mkdocs from 0.15.3 to 1.1.2

### PR DESCRIPTION
**Pull request by joshdholtz**
Super old

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>mkdocs.yml</code> was modified - make sure no modification was made by mistake</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">It seems like the page <code>_Swift: getting-started/ios/fastlane-swift.md</code> got removed from mkdocs.yml, we don't want to remove any public links. Instead please add a redirect to the new page.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">It seems like the page <code>FAQs: faqs.md</code> got removed from mkdocs.yml, we don't want to remove any public links. Instead please add a redirect to the new page.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by janpio** [comment]
What a jump

**Comment by joshdholtz** [comment]
@janpio This was a whole thing 😛 I’ve been putting it off for so long but this will feel so much better

**Comment by janpio** [comment]
Oh I know, I took an attempt last year as well :D

**Comment by joshdholtz** [comment]
> Oh I know, I took an attempt last year as well :D

I wouldn’t wish this process on anybody 😛

**Comment by ainame** [comment]
This might have broken fastlane/fastlane's CI possibly? 🤔 

https://app.circleci.com/pipelines/github/fastlane/fastlane/3543/workflows/dfdf93f9-c598-4aea-a2f4-129dbf8a05ca/jobs/74225  

```
/Users/satoshinamai/.ghq/github.com/ainame/fastlane/fastlane/lib/fastlane/documentation/markdown_docs_generator.rb:178:in `generate!': \e[31m[!] undefined method `find' for nil:NilClass\e[0m (NoMethodError)
	from Fastfile:494:in `generate_markdown_docs'
	from Fastfile:380:in `block (2 levels) in parsing_binding'
	from Fastfile:485:in `block (3 levels) in clone_docs'
	from Fastfile:484:in `chdir'
	from Fastfile:484:in `block (2 levels) in clone_docs'
	from Fastfile:482:in `chdir'
	from Fastfile:482:in `block in clone_docs'
	from /Users/satoshinamai/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tmpdir.rb:96:in `mktmpdir'
	from Fastfile:481:in `clone_docs'
	from Fastfile:379:in `block in parsing_binding'
	from /Users/satoshinamai/.ghq/github.com/ainame/fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/satoshinamai/.ghq/github.com/ainame/fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/satoshinamai/.ghq/github.com/ainame/fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/satoshinamai/.ghq/github.com/ainame/fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/satoshinamai/.ghq/github.com/ainame/fastlane/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
```

I got this stacktrace when running it locally.

**Comment by joshdholtz** [comment]
@ainame Ah sorry, just seeing that now! A rebase should fix it but it looks like you got that working already? 🙃

**Pull request merged**
