### PR TITLE
add no javascript redir info

### PR DESCRIPTION
**Pull request by muescha**

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for the PR. What is this for? Only for browsers with no Javascript?

**Comment by muescha** [comment]
yes. when javascript is disabled in browser

**Comment by muescha** [comment]
BTW: no need for `cla` in this repo?

**Comment by mfurtak** [comment]
Good point, something is not right with that. Please comment once more?

**Comment by muescha** [comment]
📖

**Comment by muescha** [comment]
✅

**Comment by KrauseFx** [comment]
I'm not sure, are there still browsers/people with no Javascript and do we have/want to support it?

**Comment by KrauseFx** [comment]
I'm sure fastlane.tools is pretty broken without JS too

**Comment by muescha** [comment]
yes a little - as i see in a first overview: 

- code snippets are not visible 
- search is not working

**Comment by muescha** [comment]
but i think for search engines it would be better to do a `301 Moved Permanently` redirect ... but you can't do this with plain html / javascript :( 

some old information mention that google also count `<head><meta http-equiv="refresh" content="0; url=#{to}"></head>` like a `301`

**Comment by KrauseFx** [comment]
Thanks for clarifying. For now, I think we'll just leave it as is 👍 :)

**Pull request closed without merging**
