### PR TITLE
[Experiment] Add proselint

### PR DESCRIPTION
**Pull request by KrauseFx**
Looks pretty solid https://github.com/amperser/proselint

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
### Proselint found issues

#### [docs/Advanced.md](/fastlane/docs/tree/prose/docs/Advanced.md)

Line | Message | Severity |
| --- | ----- | ----- |
17 | '...' is an approximation, use the ellipsis symbol '…'. Found 26 times elsewhere. | warning
21 | '...' is an approximation, use the ellipsis symbol '…'. | warning
25 | '...' is an approximation, use the ellipsis symbol '…'. | warning
44 | Use curly quotes “”, not straight quotes "". | warning
167 | Use curly quotes “”, not straight quotes "". | warning
#### [docs/CONTRIBUTING.md](/fastlane/docs/tree/prose/docs/CONTRIBUTING.md)

Line | Message | Severity |
| --- | ----- | ----- |
127 | Redundancy. Use 'I' instead of 'I personally'. | warning
154 | '...' is an approximation, use the ellipsis symbol '…'. | warning
#### [docs/FAQs.md](/fastlane/docs/tree/prose/docs/FAQs.md)

Line | Message | Severity |
| --- | ----- | ----- |
49 | '...' is an approximation, use the ellipsis symbol '…'. | warning
68 | '...' is an approximation, use the ellipsis symbol '…'. | warning
#### [docs/actions/Actions.md](/fastlane/docs/tree/prose/docs/actions/Actions.md)

Line | Message | Severity |
| --- | ----- | ----- |
118 | '...' is an approximation, use the ellipsis symbol '…'. Found 27 times elsewhere. | warning
123 | '...' is an approximation, use the ellipsis symbol '…'. | warning
131 | '...' is an approximation, use the ellipsis symbol '…'. | warning
149 | Use curly quotes “”, not straight quotes "". Found 101 times elsewhere. | warning
254 | Use curly quotes “”, not straight quotes "". | warning
1573 | Inconsistent spacing after period (1 vs. 2 spaces). | warning
1753 | Redundancy. Use 'sure' instead of 'absolutely sure'. | warning
#### [docs/best-practices/ContinuousIntegration.md](/fastlane/docs/tree/prose/docs/best-practices/ContinuousIntegration.md)

Line | Message | Severity |
| --- | ----- | ----- |
131 | Inconsistent spacing after period (1 vs. 2 spaces). | warning
131 | Inconsistent spacing after period (1 vs. 2 spaces). | warning
136 | Use curly quotes “”, not straight quotes "". | warning
151 | Inconsistent spacing after period (1 vs. 2 spaces). | warning
156 | Substitute 'damn' every time you're inclined to write 'very;' your editor will delete it and the writing will be just as it should be. | warning
156 | Inconsistent spacing after period (1 vs. 2 spaces). | warning
156 | Inconsistent spacing after period (1 vs. 2 spaces). | warning
187 | Inconsistent spacing after period (1 vs. 2 spaces). | warning
#### [docs/best-practices/Gitignore.md](/fastlane/docs/tree/prose/docs/best-practices/Gitignore.md)

Line | Message | Severity |
| --- | ----- | ----- |
#### [docs/best-practices/Keys.md](/fastlane/docs/tree/prose/docs/best-practices/Keys.md)

Line | Message | Severity |
| --- | ----- | ----- |
39 | '...' is an approximation, use the ellipsis symbol '…'. | warning
39 | Use curly quotes “”, not straight quotes "". | warning
62 | '...' is an approximation, use the ellipsis symbol '…'. | warning
62 | Use curly quotes “”, not straight quotes "". | warning
#### [docs/codesigning/CommonIssues.md](/fastlane/docs/tree/prose/docs/codesigning/CommonIssues.md)

Line | Message | Severity |
| --- | ----- | ----- |
15 | Use curly quotes “”, not straight quotes "". | warning
32 | '...' is an approximation, use the ellipsis symbol '…'. | warning
#### [docs/codesigning/GettingStarted.md](/fastlane/docs/tree/prose/docs/codesigning/GettingStarted.md)

Line | Message | Severity |
| --- | ----- | ----- |
#### [docs/codesigning/Troubleshooting.md](/fastlane/docs/tree/prose/docs/codesigning/Troubleshooting.md)

Line | Message | Severity |
| --- | ----- | ----- |
25 | '...' is an approximation, use the ellipsis symbol '…'. | warning
49 | Use curly quotes “”, not straight quotes "". | warning
#### [docs/codesigning/XcodeProject.md](/fastlane/docs/tree/prose/docs/codesigning/XcodeProject.md)

Line | Message | Severity |
| --- | ----- | ----- |
9 | Use curly quotes “”, not straight quotes "". Found 5 times elsewhere. | warning
13 | Use curly quotes “”, not straight quotes "". | warning
15 | Redundancy. Use 'drop' instead of 'drop down,'. | warning
48 | '...' is an approximation, use the ellipsis symbol '…'. | warning
#### [docs/getting-started/android/beta-deployment.md](/fastlane/docs/tree/prose/docs/getting-started/android/beta-deployment.md)

Line | Message | Severity |
| --- | ----- | ----- |
17 | '...' is an approximation, use the ellipsis symbol '…'. Found 6 times elsewhere. | warning
37 | More than 30 ppm of exclamations. Keep them under control. | warning
146 | Use curly quotes “”, not straight quotes "". Found once elsewhere. | warning
151 | Use curly quotes “”, not straight quotes "". | warning
#### [docs/getting-started/android/release-deployment.md](/fastlane/docs/tree/prose/docs/getting-started/android/release-deployment.md)

Line | Message | Severity |
| --- | ----- | ----- |
30 | More than 30 ppm of exclamations. Keep them under control. | warning
58 | '...' is an approximation, use the ellipsis symbol '…'. | warning
#### [docs/getting-started/android/screenshots.md](/fastlane/docs/tree/prose/docs/getting-started/android/screenshots.md)

Line | Message | Severity |
| --- | ----- | ----- |
3 | More than 30 ppm of exclamations. Keep them under control. | warning
9 | Stop yelling. Keep your exclamation points under control. | warning
66 | Inconsistent spacing after period (1 vs. 2 spaces). | warning
67 | Inconsistent spacing after period (1 vs. 2 spaces). | warning
#### [docs/getting-started/android/setup.md](/fastlane/docs/tree/prose/docs/getting-started/android/setup.md)

Line | Message | Severity |
| --- | ----- | ----- |
23 | More than 30 ppm of exclamations. Keep them under control. | warning
30 | Use curly quotes “”, not straight quotes "". Found once elsewhere. | warning
62 | Use curly quotes “”, not straight quotes "". | warning
75 | No hyphen is necessary in phrasal adjectives with an adverb ending in -ly. | warning
#### [docs/getting-started/ios/appstore-deployment.md](/fastlane/docs/tree/prose/docs/getting-started/ios/appstore-deployment.md)

Line | Message | Severity |
| --- | ----- | ----- |
69 | '...' is an approximation, use the ellipsis symbol '…'. | warning
#### [docs/getting-started/ios/beta-deployment.md](/fastlane/docs/tree/prose/docs/getting-started/ios/beta-deployment.md)

Line | Message | Severity |
| --- | ----- | ----- |
105 | Use curly quotes “”, not straight quotes "". | warning
#### [docs/getting-started/ios/screenshots.md](/fastlane/docs/tree/prose/docs/getting-started/ios/screenshots.md)

Line | Message | Severity |
| --- | ----- | ----- |
3 | More than 30 ppm of exclamations. Keep them under control. | warning
18 | 'It goes without saying' is a cliché. | warning
20 | '...' is an approximation, use the ellipsis symbol '…'. | warning
26 | Redundancy. Use 'same' instead of 'same exact'. | warning
#### [docs/getting-started/ios/setup.md](/fastlane/docs/tree/prose/docs/getting-started/ios/setup.md)

Line | Message | Severity |
| --- | ----- | ----- |
21 | Use curly quotes “”, not straight quotes "". | warning
#### [docs/index.md](/fastlane/docs/tree/prose/docs/index.md)

Line | Message | Severity |
| --- | ----- | ----- |
#### [docs/intro/Android.md](/fastlane/docs/tree/prose/docs/intro/Android.md)

Line | Message | Severity |
| --- | ----- | ----- |
#### [docs/intro/Appfile.md](/fastlane/docs/tree/prose/docs/intro/Appfile.md)

Line | Message | Severity |
| --- | ----- | ----- |
#### [docs/plugins/AvailablePlugins.md](/fastlane/docs/tree/prose/docs/plugins/AvailablePlugins.md)

Line | Message | Severity |
| --- | ----- | ----- |
#### [docs/plugins/CreatePlugin.md](/fastlane/docs/tree/prose/docs/plugins/CreatePlugin.md)

Line | Message | Severity |
| --- | ----- | ----- |
77 | Use curly quotes “”, not straight quotes "". Found 5 times elsewhere. | warning
81 | Use curly quotes “”, not straight quotes "". | warning
#### [docs/plugins/PluginsTroubleshooting.md](/fastlane/docs/tree/prose/docs/plugins/PluginsTroubleshooting.md)

Line | Message | Severity |
| --- | ----- | ----- |


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by mfurtak** [comment]
I generally like the things this is telling us, but the report is a bit intense. Will it avoid creating entries for files with no problems in the future?

**Comment by KrauseFx** [comment]
@mfurtak Yah, it was just a late night experiment - We can disable certain warnings/errors, and also we should fix all remaining issues we agree with. This way, only the newly introduced issues will be reported. 

The danger plugin is based on Ruby and can easily be customised, I was thinking of 2 improvements:

- Don't list empty files
- Link to the line of the file directly on the `Line` column.

**Comment by danasilver** [comment]
Looks great for more uniform docs. I agree it would be better without entries for files without issues.

It would be nice to disable the curly quotes rule (under typography.symbols) since it's picking up straight quotes in code blocks, where we want them, but it doesn't look possible without disabling all symbols checks.

**Comment by KrauseFx** [comment]
I'll close this for now, interesting concept, but not worth spending more time on right now 👍

**Pull request closed without merging**
