### PR TITLE
Update the recommended .gitignore

### PR DESCRIPTION
**Pull request by jhahn21**
Updates the recommended `.gitignore` to work recursively.

The related issue is https://github.com/fastlane/fastlane/issues/13665

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for your contribution, we can merge this as soon as we have a green CLA :)

**Comment by jhahn21** [comment]
I signed it!

**Comment by jhahn21** [comment]
@KrauseFx does it make sense to update https://github.com/dvcs/gitignore/blob/master/templates/fastlane.gitignore too?

PS: I signed it. Is there anything that I have to do to pass cla?

**Comment by KrauseFx** [comment]
Cool, perfect, thanks. Yes, actually https://github.com/github/gitignore is a widely used gitignore repo, that would make a lot of sense 👍 thanks

**Pull request merged**
