### PR TITLE
Grammatical correction

### PR DESCRIPTION
**Pull request by brendanpettis**

### CODE REVIEW

**Comment by brendanpettis** [comment]
@googlebot I signed it!

**Comment by minuscorp** [comment]
Seems like you didn't use your GitHub credentials to push the change, so the CLA cannot be signed, try amending the commit and force-pushing again.

**Comment by brendanpettis** [comment]
@googlebot I fixed it.

**Comment by brendanpettis** [comment]
@minuscorp fixed it thanks!

**Review by joshdholtz — APPROVED** [review]
❤️ Thank you!!!

**Pull request merged**
