### PR TITLE
update Google Credentials setup instructions to match current process

### PR DESCRIPTION
**Pull request by swrobel**
The process has changed substantially, so I documented what it was today when I completed it to help others.

### CODE REVIEW

**Comment by swrobel** [comment]
@googlebot I signed it!

**Review by rogerluan — COMMENTED** [review]
Hi @swrobel 👋 

Thanks for having the initiative to fix these instructions! 

Could you be so kind and attach associated images to each step on this PR description so that we can compare expected results with actual results when reviewing? Similar to what was done in this PR: https://github.com/fastlane/docs/pull/1031

There have been cases where Google was "a/b testing" console changes (or like enabling opt-in "new design") in the past, so I just wanna be more certain that we're on the same page 🙏 

I appreciate the effort! 💪

**Comment by swrobel** [comment]
@rogerluan ping!

**Comment by rogerluan** [comment]
Thanks for pinging me @swrobel ! These changes LGTM. Could you rebase your branch so it can pass CI? 🙏

**Review by rogerluan — APPROVED** [review]
🎯

**Comment by swrobel** [comment]
> Thanks for pinging me @swrobel ! These changes LGTM. Could you rebase your branch so it can pass CI? 🙏

Done!

**Review by rogerluan — APPROVED** [review]
Thank you for your contribution @swrobel ! ❤️

**Pull request merged**
