### PR TITLE
add gradle lane_contexts

### PR DESCRIPTION
**Pull request by starhoshi**
Add lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH] generated by `gradle`.

### CODE REVIEW

**Comment by starhoshi** [comment]
I signed it!

**Comment by mfurtak** [comment]
Hi @starhoshi 👋 

Thanks for this addition 👍  While you are making this change, can you also include the other variables that the `gradle` action exposes?

https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/gradle.rb#L146

Thanks!

**Comment by starhoshi** [comment]
Hi @mfurtak 😄 

Thank you for checking 👍 
I added all gradle lane_context.

Thanks!

**Comment by mfurtak** [comment]
🚀

**Pull request merged**
