### PR TITLE
Add missing comma in code block

### PR DESCRIPTION
**Pull request by JanNash**
I'd also propose the last line of the above pr template to be updated to
...(https://github.com/fastlane/fastlane or plugin repository) as they will be updated here regularly.

P.S.: I'm quite happy with fastlane, just started using it and I think it's pretty awesome, thanks and keep up the good work :). I didn't encounter any issues with the tool itself so far, so after I stumbled upon this tiny typo, I thought I could maybe contribute a bit this way :D

### CODE REVIEW

**Comment by JanNash** [comment]
Thanks googlebot, I'd forgotten that fastlane does belong to google now :D. Do I have to sign the cla for just a comma? In that case, I'd consider pulling the pull request (excuse the pun :)) and creating an issue instead? Would I have to sign the cla for an issue, too? :)

**Comment by getaaron** [comment]
You don’t need to sign the CLA for just an issue :)

**Comment by JanNash** [comment]
But for a comma? 😄

**Comment by KrauseFx** [comment]
Hey @JanNash, sorry for the troubles around that CLA. Let's close this PR, and I'll submit a bugfix for the change, just to be on the safe side 👍 Thanks for the PR and thanks for your help!

**Comment by JanNash** [comment]
No worries, sure thing :)

**Pull request closed without merging**
