### PR TITLE
Add default values to gym parameters

### PR DESCRIPTION
**Pull request by revolter**
This should be added for the other tools as well!

### CODE REVIEW

**Comment by KrauseFx** [comment]
Those files are auto-generated actually, we can't modify it here, check out the fastlane main repo for the generation code 👍

**Comment by KrauseFx** [comment]
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/documentation/markdown_docs_generator.rb and https://github.com/fastlane/fastlane/blob/master/fastlane/lib/assets/ActionDetails.md.erb

**Comment by revolter** [comment]
I thought so, and I actively searched for something like this, but couldn't find it, neither in this repo's README nor in the main repo's CONTRIBUTING.

**Comment by revolter** [comment]
How do I build the docs?

**Comment by janpio** [comment]
_That_ is indeed documented at https://github.com/fastlane/docs#fastlane-docs

The other points you mentioned... not so much. Have the same problem all the time, I think it is mostly because stuff is being moved from the repo READMEs to the docs right now.

Feel free to do write stuff down you learn though, I at least would appreciate it.

**Comment by revolter** [comment]
@janpio, are you referring to `mkdocs serve`? Or am I missing something?

Isn't that building the HTML pages from the Markdown files? I wanted to build the Markdown files from the Ruby source files.

I, having only one PR made, find it quite difficult to contribute to Fastlane, due to the missing or hard to find instructions on how to do stuff, and it being split into multiple documents like https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md and https://github.com/fastlane/fastlane/blob/master/CORE_CONTRIBUTOR.md for example.

I finally managed (after hours of searching docs) to do it by commenting out these lines:

https://github.com/fastlane/fastlane/blob/c7c6a5a4f5957a979245cc1b76314cdd0309f33e/fastlane/Fastfile#L205-L214

and running `bundle exec fastlane update_docs`, and a couple of minutes to figure out (I didn't read the verbose logs at first) that the generated Markdown files were in the temp folder.

Also, one thing I don't understand is that running `fastlane` automatically generates a `README.md` file with the available lanes, but I couldn't find it in `fastlane/fastlane` repo.

**Comment by janpio** [comment]
> are you referring to mkdocs serve? Or am I missing something?

That was the only I myself knew about - seems it wasn't enough.

Now that you know how it works, please write it down somewhere. As it is about how to work on the docs, it porbably belongs in a .md file in the docs repo I would say - but that is also just a guess.

**Comment by janpio** [comment]
> Also, one thing I don't understand is that running fastlane automatically generates a README.md file with the available lanes, but I couldn't find it in fastlane/fastlane repo.

That should probably be an issue for the fastlane/fastlane repo then, that this file is missing. Or are you looking for where this file is generated?

**Comment by revolter** [comment]
> Now that you know how it works, please write it down somewhere.

I don't think commenting out lines in a file and running it is a good solution though.

> That should probably be an issue for the fastlane/fastlane repo then, that this file is missing. Or are you looking for where this file is generated?

I think it's not generated at all, but I don't understand why.

**Pull request closed without merging**
