### PR TITLE
Add link to GitHub in footer

### PR DESCRIPTION
**Pull request by KrauseFx**
screenshot 2016-09-01 15 17 29

👍

### CODE REVIEW

**Comment by danasilver** [comment]
Can we get the [Star] button aligned vertically with the fastlane logo? Maybe just some extra margin on the top? 

Looks good, though! 👍

**Comment by KrauseFx** [comment]
@danasilver I tried to, but failed, could you change that? Feel free to change it right on this PR 👍

**Comment by danasilver** [comment]
screen shot 2016-09-01 at 5 56 30 pm

**Comment by KrauseFx** [comment]
magic, thanks 👍

**Pull request merged**
