### PR TITLE
[Bot] Update docs for latest fastlane release 2.219.0 (actions.md, available-plugins.md) 🚀

### PR DESCRIPTION
**Pull request by joshdholtz**
Auto-generated by _fastlane_ bot 🤖

Closes #1228
Closes #1227

### CODE REVIEW

**Comment by lacostej** [comment]
I rebased on latest master, after adding @rogerluan CI's fix.

**Comment by rogerluan** [comment]
Build had failed:

image

I pushed a commit that might fix it, let's see.

**Review by rogerluan — APPROVED** [review]
👍

**Review by lacostej — APPROVED** [review]

**Comment by rogerluan** [comment]
Superseded by https://github.com/fastlane/docs/pull/1243

**Pull request closed without merging**
