### PR TITLE
Move autogenerated files before building docs

### PR DESCRIPTION
**Pull request by lucgrabowski**
### Motivation and context
`actions.md`, actions documentation and `available-plugins.md` should be copied from `docs/generated` before building docs.

**This PR should be considered together with:** https://github.com/fastlane/fastlane/pull/19322
 
### Description

Changes:
Added `mkdocs-simple-hooks` plugin in `mkdocs.yml` to run python script that copies generated files:
- `generated/actions.md` to `actions.md`
- `generated/actions` directory to `actions`
- `generated/available-plugins.md` to `plugins/available-plugins.md`

### Testing Steps

Install mkdocs locally, build site, check html pages.

### CODE REVIEW

**Review by janpio — COMMENTED** [review]
Looks good to me naively - but someone should try it before merging (or trust @lucgrabowski a lot :D )

**Comment by lucgrabowski** [comment]
And I think that if it get's merged it should be coordinated with https://github.com/fastlane/fastlane/pull/19322 and get merged before fastlane's PR.
I have a feeling that the order of merging this PR and https://github.com/fastlane/docs/pull/1092 shouldn't matter.

**Review by joshdholtz — CHANGES_REQUESTED** [review]
@lucgrabowski The Netlify preview isn't building 😱 I think that this dependency needs to be added to the Pipfile?

```
6:16:10 PM: ERROR   -  Config value: 'plugins'. Error: The "mkdocs-simple-hooks" plugin is not installed
6:16:10 PM: Aborted with 1 Configuration Errors!
```

**Comment by lucgrabowski** [comment]
Now it's 
> FileNotFoundError: [Errno 2] No such file or directory: 'docs/actions'

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
This looks great! I love that we have this new generated directory 😊 Going to merge this and then merge the other PR in the main fastlane repo 

Thank you so much! 🙌

**Comment by rogerluan** [comment]
I'm so glad we got this in! 🤩 Thank you @lucgrabowski @janpio and @joshdholtz for making this a reality 🚀

**Pull request merged**
