### PR TITLE
Remove contribution docs from docs page

### PR DESCRIPTION
**Pull request by KrauseFx**
This will live in the main repo instead

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true"><code>mkdocs.yml</code> was modified - make sure no modification was made by mistake</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">It seems like the page <code>UI: contributing/UI.md</code> got removed from mkdocs.yml, we don’t want to remove any public links. Instead please add a redirect to the new page.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="true">It seems like the page <code>Contribution Guidelines: contributing/CONTRIBUTING.md</code> got removed from mkdocs.yml, we don’t want to remove any public links. Instead please add a redirect to the new page.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by mfurtak** [comment]
I think I'd like to discuss this a little more before removing it.

**Comment by KrauseFx** [comment]
That works for me. We could also have them somehow folded, so that they don't take up as much space.

**Comment by KrauseFx** [comment]
Conflicts, let's close this

**Pull request closed without merging**
