### PR TITLE
Generalize source control recommendations guide

### PR DESCRIPTION
**Pull request by bgannin**
Add guide for ignoring in Mercurial as well for consistency.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for the PR. This isn't linked on the sidebar, and I'm not sure I want to add a second menu entry to the sidebar. How about we have `Source Control` as the title, and this contains both git and mercurial?

**Comment by bgannin** [comment]
Sure, will do.

**Comment by KrauseFx** [comment]
Make sure to add an entry to https://github.com/fastlane/docs/blob/master/scripts/ci/available_redirects.rb to not break any links

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>

    <tr>
      <td>:warning:</td>
      <td data-sticky="true"><code>mkdocs.yml</code> was modified - make sure no modification was made by mistake</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by bgannin** [comment]
I couldn't find what else needed to be updated for the capitalization…

**Comment by KrauseFx** [comment]
This is great, thanks 👍

**Pull request merged**
