### PR TITLE
Update running-tests.md

### PR DESCRIPTION
**Pull request by PF93mc8y7erq92qTmTjJBysALa**
fix copy-paste error; no need to refer to ios tests for ci from android getting started document

### CODE REVIEW

**Comment by KrauseFx** [comment]
Oh could you also sign the CLA? :) Thanks

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
seems i may not manage to address the google cla in a timely manner. feel free to implement the change in the meanwhile

**Comment by KrauseFx** [comment]
Thanks, no worries, appreciate your help 👍 Applied the fix separately

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
Thanks.

It was not clear to me how I could sign the google cla and/or associate this github account with a signed google cla. That is, it was not clear if I needed a google account to do so.

And thanks again for _fastlane_.

**Comment by taquitos** [comment]
Yeah, it's kinda confusing 😞

**Pull request closed without merging**
