### PR TITLE
Light sidenav with fastlane blue links.

### PR DESCRIPTION
**Pull request by danasilver**
A first pass at a light sidenav. Tried to maintain similar features to readthedocs/docs.fabric.io:

* Bold indicates current page.
* Easily distinguish between links and non-clickable categories.
* Distinguish between pages and page sections.

Some new things:

* Larger font for better readability.
* Fastlane blue!

Since this was the first big style PR, I took the opportunity to split up fabric.css into some major topics (sidenav, code, breadcrumbs) to make it easier to work with. I removed the Font Awesome selectors since they're already present in the readthedocs theme we're extending.

Desktop:

screen shot 2016-09-02 at 1 28 58 am

Mobile without menu showing:

screen shot 2016-09-02 at 1 41 07 am

### CODE REVIEW

**Comment by KrauseFx** [comment]
This is great 👍

**Comment by danasilver** [comment]
Updated version: 
image

**Comment by danasilver** [comment]
👍 💯  Looks good!

**Comment by KrauseFx** [comment]
This is AWESOME, let's do this 🚀

**Pull request merged**
