### PR TITLE
Visited links shouldn’t be purple

### PR DESCRIPTION
**Pull request by KrauseFx**
Visited links shown in purple is so 2000

### CODE REVIEW

**Comment by mfurtak** [comment]
If purple looks too retro, or doesn't fit our color scheme, I think that's OK. However, my opinion is that making `visited` have no difference in color at all is a negative for usability of the web.

**Comment by KrauseFx** [comment]
But no website does a different color for visited any more, e.g. 

- GitHub
- Ruby Docs http://ruby-doc.org/
- React Docs https://facebook.github.io/react/index.html

**Comment by mfurtak** [comment]
That's cool, it's just my opinion :smile:. We can do whatever we want 👍

**Comment by KrauseFx** [comment]
If you're ok with it, I'd merge this 👍

**Comment by mfurtak** [comment]
🆗 🚢

**Comment by KrauseFx** [comment]
👍

**Comment by mfurtak** [comment]
To capture some stuff that has better expressed my thinking, in case we want to reconsider later:

- https://www.smashingmagazine.com/2010/02/the-definitive-guide-to-styling-web-links/#dont-forget-about-visited-links
- http://ux.stackexchange.com/a/38007

**Pull request merged**
