### PR TITLE
[Bot] Update docs for latest fastlane release 2.195.0 (actions.md, available-plugins.md) 🚀

### PR DESCRIPTION
**Pull request by joshdholtz**
Auto-generated by _fastlane_ bot 🤖

### CODE REVIEW

**Comment by revolter** [comment]
@googlebot I consent

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>mkdocs.yml</code> was modified - make sure no modification was made by mistake</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">It seems like the page <code>crashlytics: actions/crashlytics.md</code> got removed from mkdocs.yml, we don't want to remove any public links. Instead please add a redirect to the new page.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by revolter** [comment]
Because https://github.com/fastlane/fastlane/pull/19371 removed an action, the documentation for it needed to be removed too, but manually (or so it looks), so I did it on this branch, to fix the failing tests.

I also added a redirect, but I can't test it locally.

**Review by revolter — APPROVED** [review]

**Comment by revolter** [comment]
The redirect works: https://docs.fastlane.tools/actions/crashlytics 😌

**Pull request merged**
