### PR TITLE
fix path of FastlaneSwiftRunner.xcodeproj

### PR DESCRIPTION
**Pull request by gijima-alasdair**
Updated to use correct directory location of FastlaneSwiftRunner.xcodeproj

### CODE REVIEW

**Review by minuscorp — APPROVED** [review]
LGTM

**Comment by gijima-alasdair** [comment]
I've signed the CLA and replied to email.

**Comment by minuscorp** [comment]
Comment here `@googlebot I signed it!`

**Comment by gijima-alasdair** [comment]
`@googlebot I signed it!`

**Review by rogerluan — APPROVED** [review]
👍 Thanks for your contribution!

**Pull request merged**
