### PR TITLE
docs(react-native): Add new link to tutorial using detox for screenshotting

### PR DESCRIPTION
**Pull request by BatDroid**
A new link is added as a tutorial for having automatic screenshots in a react native project with Fastlane & Detox

### CODE REVIEW

**Comment by BatDroid** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Comment by janpio** [comment]
Interesting. `screengrab` didn't work because its automation doesn't work well with React Native? https://docs.fastlane.tools/actions/screengrab/#ui-tests

**Comment by BatDroid** [comment]
> Interesting. `screengrab` didn't work because its automation doesn't work well with React Native? https://docs.fastlane.tools/actions/screengrab/#ui-tests

what i understood from the auto screenshot for both ios & android(screengrab) was that they needed native setup, linking, etc. so it wasn't very clear for a react native developer who want to have auto screenshot with minimum effort.

**Comment by janpio** [comment]
That sounds very reasonable and is an avenue we should look into further from fastlane itself.

**Comment by BatDroid** [comment]
> That sounds very reasonable and is an avenue we should look into further from fastlane itself.

so do you see this pr/article good enough to be merged until fastlane provide something for it?

**Review by joshdholtz — APPROVED** [review]
This looks good to me! Thanks for the contribution and sorry about the slow review 🤦‍♂️

**Pull request merged**
