### PR TITLE
Add turbolinks for instant page reloads

### PR DESCRIPTION
**Pull request by buger**
You have one of the best documentations I ever seen, be we can make it even better with faster page reloads.

This change add small (30kb) js library called Turbolinks, which automatically will be loaded by mkdocs, which gives almost instant page reloads.

Project page https://github.com/turbolinks/turbolinks

> Turbolinks makes navigating your web application faster. Get the performance benefits of a single-page application without the added complexity of a client-side JavaScript framework. Use HTML to render your views on the server side and link to pages as usual. When you follow a link, Turbolinks automatically fetches the page, swaps in its <body>, and merges its <head>, all without incurring the cost of a full page load.

I checked on mkdoc based site, and it worked great!
But for sure require a bit more testing since you have a lot of different pages.

### CODE REVIEW

**Comment by buger** [comment]
I believe last failed test not caused by me: "Could not set up API to Code Review site for Danger"

**Comment by KrauseFx** [comment]
Yeah, don't worry about the test failure for now, for security reasons we can't run danger for external PRs.

**Comment by buger** [comment]
Not sure what you mean, `mkdocs` automatically loads all files from `js` and `css` folders. If you want, I can add explicit `extra_js` option to `mkdocs` config.

**Comment by KrauseFx** [comment]
Ah, alright, I didn't know that 👍

**Comment by KrauseFx** [comment]
Just tested this locally, works great 👍  Thanks for your contribution

**Pull request merged**
