### PR TITLE
Add new fastlane installation header to most docs pages

### PR DESCRIPTION
**Pull request by KrauseFx**
screenshot 2018-01-06 10 44 27

screenshot 2018-01-06 10 44 29

### CODE REVIEW

**Comment by janpio** [comment]
Added extension is missing from https://github.com/fastlane/docs/blob/master/requirements.txt which makes CI fail.

**Comment by KrauseFx** [comment]
Thanks @janpio, updated 👍

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>mkdocs.yml</code> was modified - make sure no modification was made by mistake</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by janpio** [comment]
Now you have a proper test failure :)

```
[16:14:19]: -------------------------------------------
[16:14:19]: --- Step: Switch to ensure_headers lane ---
[16:14:19]: -------------------------------------------
[16:14:19]: Cruising over to lane 'ensure_headers' 🚖
[16:14:19]: 🕗  Investigating all docs files and their headers...
[16:14:19]: File 'docs/advanced.md' doesn't start with #
[16:14:19]: File 'docs/best-practices/continuous-integration.md' doesn't start with #
[16:14:19]: File 'docs/codesigning/getting-started.md' doesn't start with #
[16:14:19]: File 'docs/codesigning/xcode-project.md' doesn't start with #
[16:14:19]: File 'docs/getting-started/android/beta-deployment.md' doesn't start with #
[16:14:19]: File 'docs/getting-started/android/release-deployment.md' doesn't start with #
[16:14:19]: File 'docs/getting-started/android/screenshots.md' doesn't start with #
[16:14:19]: File 'docs/getting-started/ios/appstore-deployment.md' doesn't start with #
[16:14:19]: File 'docs/getting-started/ios/beta-deployment.md' doesn't start with #
[16:14:19]: File 'docs/getting-started/ios/screenshots.md' doesn't start with #
[16:14:19]: File 'docs/setup-fastlane-header.md' doesn't start with #
+---------------+------+
|     Lane Context     |
+---------------+------+
| PLATFORM_NAME |      |
| LANE_NAME     | test |
+---------------+------+
[16:14:19]: At least one file doesn't start with header one (# or <!--), the first line must always be # title or <!-- comment
```

**Comment by KrauseFx** [comment]
Thanks for directly fixing it @janpio, pushed another commit now 👍

**Pull request merged**
