### PR TITLE
Remove duplicate entry in OCLint docs

### PR DESCRIPTION
**Pull request by colmdoyle**
`select_regex` was appearing twice.

### CODE REVIEW

**Comment by hjanuschka** [comment]
awesome many thx for your contribution 🚀 
can you follow the @googlebot  and sign the CLA?

**Comment by colmdoyle** [comment]
No worries, all signed now.

**Comment by KrauseFx** [comment]
That's weird. The `Action.md` is auto-generated. I wonder why there is a duplicate entry?

**Comment by colmdoyle** [comment]
Since this is auto-generated, better close this and figure out the root cause.

**Pull request closed without merging**
