### PR TITLE
Fix links to advanced docs

### PR DESCRIPTION
**Pull request by rajivshah3**
Fixes broken links to advanced docs

### CODE REVIEW

**Comment by rajivshah3** [comment]
I signed it!

**Comment by rajivshah3** [comment]
Ahh yikes, didn't realize that the links were for `https://docs.fastlane.tools`. I'll have to figure out what link directed me to https://github.com/fastlane/docs/blob/master/docs/advanced.md because the links on *that* page (not its equivalent on the docs website) are broken. They direct to GitHub files that don't exist. Sorry about that!

**Comment by janpio** [comment]
Oh yes, that is true - I guess most of the links on https://github.com/fastlane/docs/tree/master/docs won't work in that context. If something linked there, it should definitely be fixed. Let us know if you found it.

**Comment by rajivshah3** [comment]
Will do!

**Comment by rajivshah3** [comment]
Looks like it was just a Google search (https://www.google.com/search?q=fastlane+lane+parameters&oq=fastlane+lane+para&aqs=chrome.0.0j69i57j0l3j69i64.2630j0j1&sourceid=chrome&ie=UTF-8), it was the 3rd result

**Comment by janpio** [comment]
Hm, any idea how we could solve this?

**Comment by rajivshah3** [comment]
I guess you could ask Google to index pages such as https://docs.fastlane.tools/advanced/lanes/ <https://docs.fastlane.tools/advanced/lanes/> so that they show up in search? Not entirely sure whether that would help or if that’s already been done.

**Pull request closed without merging**
